### ISSUE TITLE
Default internalnorm

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqGPU.jl#4]
Right now the default internalnorm just does the Harier norm on the whole. However it might be better to re-weigh it by applying the Hairer norm along the individual problem slices, and then using the minimum of them. This would then make sure each trajectory is appropriately error handled instead handling the error in the average trajectory.

**Comment by ChrisRackauckas** [comment]
@vchuravy could GPUifyLoops get a reduction function?

**Comment by vchuravy** [comment]
Hm can't you just call `reduce` on the array?

**Comment by ChrisRackauckas** [comment]
It seems like CuArrays doesn't implement a fast iterator?

**Comment by ChrisRackauckas** [comment]
Oh I see what you mean.

**Comment by ChrisRackauckas** [comment]
Here's the issue. I want to use a GPUifyLoop to reduce along columns:

```julia
function reduce_kernel(u)
    @loop for i in (1:size(u,2); (blockIdx().x-1) * blockDim().x + threadIdx().x)
        @views @inbounds sum(abs2,u[:,i])
        nothing
    end
    nothing
end
```

and then I want to take the minimum of the results. I could write the result of the first operation into an array and take the minimum, but there should be something better that could be done?

**Comment by vchuravy** [comment]
>  but there should be something better that could be done?

Yeah, but probably not easily within the framework `GPUifyLoops` offers. You need to implement a fast reduce yourself and that is rather tricky.
Sum along the columns and then use a sorting net to calculate the minimum.

other wise `minimum(reduce(A, dim=1))`

**Comment by ChrisRackauckas** [comment]
Note that https://github.com/JuliaDiffEq/DiffEqGPU.jl/issues/18 means that simple workarounds like

```julia
@inline DiffEqBase.ODE_DEFAULT_NORM(u::CuArray,t) = sqrt(real(sum(abs2.(u))) / length(u))
```

are still hitting bad fallbacks. The packagized version of what @vchuravy suggested is https://github.com/JuliaDiffEq/DiffEqGPU.jl/pull/23, but that seems to be failing because reduce with dims is missing from CuArrays.
